source 'https://rubygems.org'

gem 'rails', '4.2.3'
#i added the 'group: : development' with regards to
#configuring my app for deploymet to heroku
gem 'sqlite3', group: :development
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'therubyracer', platforms: :ruby
gem 'capybara', '~> 2.4.4'
gem 'poltergeist', '~> 1.6.0'
gem 'phantomjs', '~> 1.9.8.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  gem 'spring'
end

gem 'httparty'

#i added the following 3 lines with regards to
#configuring my app for deploymet to heroku
#heroku use postgres database and hence the following
#3 lines of code
group :production do
	gem 'rails_12factor'
	#the output of running 'Houst:$ heroku run rails console'
	#in the terminal asked me to include the following pg gem
	gem 'pg'
end

